In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [14]:
df1 = pd.read_csv("EDA/data/all_womens_foil_bout_data_May_13_2021_cleaned.csv")
df1

,fencer_ID,opp_ID,fencer_age,opp_age,fencer_score,opp_score,winner_ID,fencer_curr_pts,opp_curr_pts,tournament_ID,pool_ID,upset,date
0,36796,19574,23,28,5,1,36796,12.5,7.50,2021-121,1,False,2021-03-26
1,36796,42147,23,19,5,2,36796,12.5,0.75,2021-121,1,False,2021-03-26
2,36796,49116,23,21,5,2,36796,12.5,22.25,2021-121,1,True,2021-03-26
3,36796,39631,23,18,5,4,36796,12.5,23.00,2021-121,1,True,2021-03-26
4,36796,23447,23,27,4,5,23447,12.5,79.00,2021-121,1,False,2021-03-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49126,45679,32336,34,25,5,2,45679,0.0,0.00,2018-1218,5,False,2017-12-09
49127,45679,35935,34,22,4,5,35935,0.0,3.00,2018-1218,5,False,2017-12-09
49128,36591,32336,22,25,2,5,32336,0.0,0.00,2018-1218,5,False,2017-12-09
49129,36591,35935,22,22,1,5,35935,0.0,3.00,2018-1218,5,False,2017-12-09
49130,32336,35935,25,22,0,5,35935,0.0,3.00,2018-1218,5,False,2017-12-09

In [ ]:
df2 = pd.read_csv("EDA/data/all_womens_foil_fencer_bio_data_May_13_2021_cleaned.csv")
df2

,id,name,country_code,country,hand,age,url,date_accessed
0,28761,DVORKIN Mary,ISR,ISRAEL,Left,24,https://fie.org/athletes/28761,2021-05-13 21:42:17
1,43803,SHI Yue,CHN,CHINA,Right,22,https://fie.org/athletes/43803,2021-05-13 21:35:13
2,46080,TANG Nga Hei,MAC,"MACAO, CHINA",Right,20,https://fie.org/athletes/46080,2021-05-13 21:46:21
3,46481,WONAME Kelsey Victoria Afriyie,GHA,GHANA,Right,17,https://fie.org/athletes/46481,2021-05-13 21:48:14
4,47075,BRECHERET Carolina,BRA,BRAZIL,Right,16,https://fie.org/athletes/47075,2021-05-13 21:50:07
...,...,...,...,...,...,...,...,...
2103,51177,SAAVEDRA Ana,MEX,MEXICO,Right,16,https://fie.org/athletes/51177,2021-05-13 21:30:50
2104,40429,MORE CHAVEZ Karine,CUB,CUBA,Right,25,https://fie.org/athletes/40429,2021-05-13 21:55:53
2105,51183,ADALID Maria,MEX,MEXICO,Right,17,https://fie.org/athletes/51183,2021-05-13 21:30:51
2106,51186,ESPINOSA Frida,MEX,MEXICO,Right,15,https://fie.org/athletes/51186,2021-05-13 21:30:52
2107,51193,MARTINEZ Maggie,MEX,MEXICO,Right,18,https://fie.org/athletes/51193,2021-05-13 21:30:55

In [ ]:
df3 = pd.read_csv("EDA/data/all_womens_foil_fencer_rankings_data_May_13_2021_cleaned.csv")
df3

          id weapon  category     season  rank  points
0        164   Foil  Veterans  2016/2017    78     0.0
1        164   Foil  Veterans  2016/2017    78     0.0
2        164   Foil  Veterans  2017/2018    37     0.0
3        164   Foil  Veterans  2017/2018    37     0.0
4        234   Foil    Senior  2007/2008    52    56.0
...      ...    ...       ...        ...   ...     ...
10932  53148   Foil     Cadet  2021/2022    25     0.0
10933  53148   Foil    Junior  2021/2022   213     2.5
10934  53151   Foil     Cadet  2021/2022     8     0.0
10935  53161   Foil    Junior  2021/2022   287     0.0
10936  53162   Foil    Junior  2021/2022   321     0.0

[10937 rows x 6 columns]

In [20]:
df4 = pd.read_csv("EDA/data/all_womens_foil_tournament_data_May_13_2021_cleaned.csv")
df4

,competition_ID,season,name,category,country,start_date,end_date,weapon,gender,timezone,url,unique_ID,missing_results_flag
0,121,2021,Grand Prix,Senior,QATAR,2021-03-26,2021-03-28,Foil,Womens,Asia/Qatar,https://fie.org/competitions/2021/121,2021-121,NaN
1,41,2017,Tournoi international,Junior,GERMANY,2016-10-28,2016-10-28,Foil,Womens,Europe/Berlin,https://fie.org/competitions/2017/41,2017-41,NaN
2,800,2015,Championnats PanamÃ©ricains,Senior,CHILE,2015-04-17,2015-04-26,Foil,Womens,America/Santiago,https://fie.org/competitions/2015/800,2015-800,NaN
3,243,2019,Championnats du Monde,Senior,HUNGARY,2019-07-16,2019-07-19,Foil,Womens,Europe/Budapest,https://fie.org/competitions/2019/243,2019-243,NaN
4,237,2016,Championnats du monde juniors-cadets,Cadet,FRANCE,2016-04-01,2016-04-01,Foil,Womens,Europe/Paris,https://fie.org/competitions/2016/237,2016-237,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,118,2015,Coupe du Monde,Senior,FRANCE,2014-11-07,2014-11-08,Foil,Womens,Europe/Paris,https://fie.org/competitions/2015/118,2015-118,NaN
214,1014,2015,Championnats asiatiques,Senior,SINGAPORE,2015-06-25,2015-06-30,Foil,Womens,Asia/Singapore,https://fie.org/competitions/2015/1014,2015-1014,NaN
215,122,2018,Reinhold-WÃ¼rth-Cup,Senior,GERMANY,2018-04-27,2018-04-28,Foil,Womens,Europe/Berlin,https://fie.org/competitions/2018/122,2018-122,NaN
216,127,2016,The Artus Court PKO BP,Senior,POLAND,2016-01-15,2016-01-16,Foil,Womens,Europe/Warsaw,https://fie.org/competitions/2016/127,2016-127,NaN
217,1218,2018,Tournoi satellite,Senior,TURKEY,2017-12-09,2017-12-09,Foil,Womens,Europe/Istanbul,https://fie.org/competitions/2018/1218,2018-1218,NaN